"use client";
export const skillData = [
    { name: "JavaScript", image: "/skills/js.png", category: "Frontend" },
    { name: "TypeScript", image: "/skills/ts.png", category: "Frontend" },
    { name: "NextJS", image: "/skills/nextjs.png", category: "Frontend" },
    { name: "ReactJS", image: "/skills/React.png", category: "Frontend" },

    { name: "Redux", image: "/skills/redux.png", category: "Frontend" },
    {
        name: "React-Query",
        image: "/skills/react-query.png",
        category: "Frontend",
    },
    { name: "Tailwind", image: "/skills/tailwind.png", category: "Frontend" },
    {
        name: "Material UI",
        image: "/skills/material_ui.png",
        category: "Frontend",
    },
    { name: "HTML5", image: "/skills/HTML.png", category: "Frontend" },
    { name: "CSS3", image: "/skills/css3.png", category: "Frontend" },
    { name: "Bootstrap", image: "/skills/bootstrap.png", category: "Frontend" },
    { name: "Sass", image: "/skills/sass.png", category: "Frontend" },
    { name: "jQuery", image: "/skills/jquery.png", category: "Frontend" },
    { name: "NodeJS", image: "/skills/nodejs.png", category: "Backend" },
    { name: "ExpressJS", image: "/skills/express.png", category: "Backend" },
    { name: "MongoDB", image: "/skills/mongodb.png", category: "Backend" },
    { name: "AWS", image: "/skills/aws.png", category: "Backend" },
    { name: "MySQL", image: "/skills/mysql.png", category: "Backend" },
    { name: "Redis", image: "/skills/redis.png", category: "Backend" },
    { name: "Googling", image: "/skills/google.png", category: "Others" },
    { name: "Git", image: "/skills/git.png", category: "Others" },
    { name: "GitHub", image: "/skills/github.png", category: "Others" },
    { name: "Jira", image: "/skills/jira.png", category: "Others" },
    { name: "Vercel", image: "/skills/vercel.png", category: "Others" },
    { name: "Netlify", image: "/skills/netlify.png", category: "Others" },
];